### ISSUE TITLE
Setting textwidth=75 seems arbitrary and too invasive

### ISSUE THREAD

**Issue by andreasthoelke** [goolord/vim2hs#1]
Hi! vim2hs sets the `textwidth` to 75 here
https://github.com/goolord/vim2hs/blob/74c76328ad70ee489581af04c867b9d0154698d9/autoload/vim2hs/haskell/editing.vim#L41

I'm not sure why this is needed. Is this a common practice for Haskell code?

A concern may be that it may be surprising to users and hard to find out why their text breaks at 75 characters.

**Comment by goolord** [comment]
I agree that this seems unnecessary, this line is being deleted
